name: Python package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: DOing Shit Down!!
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python ./python.py
          
      - name: lint-vint main
        run: ./timtimala.ps1
